// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://loyugrfgnobqfrboobjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxveXVncmZnbm9icWZyYm9vYmpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTE2MzksImV4cCI6MjA3Mjk4NzYzOX0.dKrMuYG-FZaAWEWC3DjrjPWk6KZtc1DUcdSnxsSTzRg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});